INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 1, 3, 2, 5, 'Шарипов Р', 17);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 0, 2, 1, 2, 'Дроздиков Валерий', 7);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 3, 12, 4, 13, 'Гизатуллин Зиннур', 48);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 1, 11, 12, 13, 'Якимов Игорь', 51);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 2, 3, 4, 6, 'Тумбинская М', 23);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 1, 0, 2, 'Тахавова Эльза', 5);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 3, 9, 4, 10, 'Чермошенцев Сергей', 39);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 1, 2, 2, 2, 'Невзоров Владимир', 10);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 0, 1, 1, 1, 'Малышев Юрий', 4);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 1, 3, 4, 'Ахметвалеев А', 12);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 1, 1, 1, 'Сытник Анатолий', 4);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 2, 4, 2, 6, 'Суздальцев Илья', 22);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 0, 1, 0, 1, 'Котельников Александр', 3);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 3, 2, 3, 'Яхина Зухра', 11);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 3, 13, 9, 18, 'Галеев Ильдар', 64);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 2, 2, 2, 'Зиновьев П ', 8);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 4, 9, 4, 10, 'Гайнутдинов Рустам', 41);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 1, 1, 2, 'Барков Игорь', 6);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 1, 1, 1, 2, 'Абзалов А', 8);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 2, 2, 2, 'Исаева Юлия', 8);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 3, 3, 4, 'Ризаев Ильдус', 14);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 1, 2, 2, 'Назаров А', 7);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 1, 14, 15, 16, 'Мокшин Владимир', 63);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 2, 3, 5, 'Александрова Л', 15);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 0, 1, 1, 1, 'Кирша Александр', 4);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 1, 3, 3, 3, 'Медведев Михаил', 14);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 3, 4, 4, 'Захарова Земфира', 15);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 0, 1, 1, 'Вафин Радик', 3);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 1, 2, 2, 'Талипов Н', 7);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 3, 2, 3, 'Корнилов Г ', 11);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 2, 4, 5, 6, 'Шлеймович Михаил', 25);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 1, 6, 12, 16, 'Катасёв А', 52);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 0, 1, 1, 2, 'Галеева Луиза', 6);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 2, 4, 4, 'Хохлов Дмитрий', 14);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 2, 2, 2, 'Осипова Алла', 8);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 1, 1, 1, 'Зарайский Сергей', 4);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 2, 1, 2, 'Зайнуллина Гульсина ', 7);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 0, 2, 1, 2, 'Кривилёв М', 7);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('САПР', 0, 3, 1, 4, 'Воронова Валентина', 12);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 1, 2, 1, 3, 'Суздальцев Владимир ', 11);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 2, 1, 2, 'Ризаев Ильгизар', 7);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 1, 7, 10, 12, 'Катасева Д', 43);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('СИБ', 3, 5, 6, 8, 'Аникин И', 33);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 5, 1, 6, 'Эминов Фарид', 18);
INSERT INTO PUBLIC.TEACHER (DEP, X1, X2, X3, X4, NAME, RATING) VALUES ('АСОИУ', 0, 5, 5, 5, 'Шарнин Леонид', 20);